### ISSUE TITLE
Code typo

### ISSUE THREAD

**Issue by jacgonisa** [Sh1ne111/SV_genotyping#1]
Cannot reproduce the line.
"{" missing before sample
"i" not iterated

Cheers!

**Comment by Sh1ne111** [comment]
> Cannot reproduce the line. "{" missing before sample "i" not iterated
> 
> Cheers!


Hi, jacgonisa

Thank you so much for catching that error in my code. I've addressed the issue. I appreciate your keen eye for detail. 

Thanks again!

Chen
